version: '3'

services:  
  db:
    image: postgres:14.2
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - env_file
    networks:
      - db_network

  app:
    build: ./app/
    command: python app.py
    networks:
      - db_network
      - web_network 
    depends_on:
      - db

  nginx:
    image: nginx:1.21.6
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  db_data: